<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

<!-- Include common properties -->
<xacro:include filename="$(find mon_urdf)/urdf/common_properties.xacro"/>

<!-- Defined properties -->
<xacro:property name="base_length" value="0.6"/>
<xacro:property name="base_width" value="0.4"/>
<xacro:property name="base_height" value="0.2"/>
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_length" value="0.05"/>
<xacro:property name="wheel_separation" value="0.45"/>
<xacro:property name="camera_length" value="0.01"/>
<xacro:property name="camera_width" value="0.05"/>
<xacro:property name="camera_height" value="0.1"/>

<!-- Links -->
<link name="base_footprint"/>

<link name="base_link">
  <visual>
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}"/>
    </geometry>
    <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}"/>
    </geometry>
    <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
  </collision>
  <xacro:box_inertia m="15.0" l="${base_length}" w="${base_width}" h="${base_height}" xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
</link>

<!-- Wheels -->
<link name="front_right_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
  </collision>
  <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
</link>

<link name="front_left_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
  </collision>
  <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
</link>

<link name="back_right_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
  </collision>
  <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
</link>

<link name="back_left_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
  </collision>
  <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
</link>

<!-- Camera -->
<link name="camera_link">
  <visual>
    <geometry>
      <box size="${camera_length} ${camera_height} ${camera_width}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 1.57"/>
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <box size="${camera_length} ${camera_height} ${camera_width}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 1.57"/>
  </collision>
  <xacro:box_inertia m="0.2" l="${camera_length}" w="${camera_height}" h="${camera_width}" xyz="0 0 0" rpy="0 0 0"/>
</link>

<!-- 3D LiDAR (Velodyne VLP-16 style) -->
<link name="velodyne_base_link">
  <visual>
    <geometry>
      <cylinder radius="0.05" length="0.07"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="green"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="0.05" length="0.07"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <xacro:cylinder_inertia m="0.83" r="0.05" h="0.07" xyz="0 0 0" rpy="0 0 0"/>
</link>

<!-- LiDAR Link (for LIO-SAM compatibility) -->
<link name="lidar_link">
  <visual>
    <geometry>
      <box size="0.1 0.1 0.05"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="green"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.1 0.1 0.05"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <xacro:box_inertia m="0.1" l="0.1" w="0.1" h="0.05" xyz="0 0 0" rpy="0 0 0"/>
</link>

<!-- IMU -->
<link name="imu_link">
  <visual>
    <geometry>
      <box size="0.02 0.02 0.01"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="yellow"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.02 0.02 0.01"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <xacro:box_inertia m="0.1" l="0.02" w="0.02" h="0.01" xyz="0 0 0" rpy="0 0 0"/>
</link>

<!-- Joints -->
<joint name="base_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
</joint>

<!-- Front wheels as passive caster wheels -->
<joint name="base_front_right_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="front_right_wheel"/>
  <origin xyz="0.15 -${wheel_separation/2.0} -${base_height / 2.0}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.1" friction="0.1"/>
</joint>

<joint name="base_front_left_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="front_left_wheel"/>
  <origin xyz="0.15 ${wheel_separation/2.0} -${base_height / 2.0}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.1" friction="0.1"/>
</joint>

<!-- Back wheels as driven wheels -->
<joint name="left_joint" type="continuous">
  <parent link="base_link"/>
  <child link="back_left_wheel"/>
  <origin xyz="-0.15 ${wheel_separation/2.0} -${base_height / 2.0}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.2" friction="1.0"/>
</joint>

<joint name="right_joint" type="continuous">
  <parent link="base_link"/>
  <child link="back_right_wheel"/>
  <origin xyz="-0.15 -${wheel_separation/2.0} -${base_height / 2.0}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.2" friction="1.0"/>
</joint>

<!-- Sensor mounts -->
<joint name="velodyne_base_mount_joint" type="fixed">
  <parent link="base_link"/>
  <child link="velodyne_base_link"/>
  <origin xyz="0 0 ${base_height / 2.0 + 0.035}" rpy="0 0 0"/>
</joint>

<!-- LiDAR link joint - CRITICAL: This defines the proper frame hierarchy -->
<joint name="velodyne_lidar_joint" type="fixed">
  <parent link="velodyne_base_link"/>
  <child link="lidar_link"/>
  <origin xyz="0 0 0.05" rpy="0 0 0"/>
</joint>

<joint name="base_imu_joint" type="fixed">
  <parent link="base_link"/>
  <child link="imu_link"/>
  <origin xyz="0.1 0 ${base_height / 2.0 + 0.005}" rpy="0 0 0"/>
</joint>

<joint name="camera_link_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="${base_length / 2.0} 0 ${base_height / 4.0}" rpy="0 0 0"/>
</joint>

<!-- Gazebo Materials -->
<gazebo reference="base_link">
  <material>Gazebo/Blue</material>
  <mu1>0.3</mu1>
  <mu2>0.3</mu2>
  <kp>10000000.0</kp>
  <kd>1000.0</kd>
</gazebo>

<gazebo reference="front_left_wheel">
  <material>Gazebo/Black</material>
  <mu1>0.5</mu1>
  <mu2>0.5</mu2>
  <kp>10000000.0</kp>
  <kd>1000.0</kd>
  <minDepth>0.001</minDepth>
  <maxVel>10.0</maxVel>
  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="front_right_wheel">
  <material>Gazebo/Black</material>
  <mu1>0.5</mu1>
  <mu2>0.5</mu2>
  <kp>10000000.0</kp>
  <kd>1000.0</kd>
  <minDepth>0.001</minDepth>
  <maxVel>10.0</maxVel>
  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="back_left_wheel">
  <material>Gazebo/Black</material>
  <mu1>2.0</mu1>
  <mu2>1.0</mu2>
  <kp>10000000.0</kp>
  <kd>1000.0</kd>
  <minDepth>0.001</minDepth>
  <maxVel>10.0</maxVel>
  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="back_right_wheel">
  <material>Gazebo/Black</material>
  <mu1>2.0</mu1>
  <mu2>1.0</mu2>
  <kp>10000000.0</kp>
  <kd>1000.0</kd>
  <minDepth>0.001</minDepth>
  <maxVel>10.0</maxVel>
  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="camera_link">
  <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="velodyne_base_link">
  <material>Gazebo/Green</material>
</gazebo>

<gazebo reference="imu_link">
  <material>Gazebo/Yellow</material>
</gazebo>

<!-- Differential Drive Plugin - CORRECTED -->
<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <ros>
      <namespace>/</namespace>
    </ros>
    
    <!-- Update rate in Hz -->
    <update_rate>50</update_rate>
    
    <!-- wheels -->
    <left_joint>left_joint</left_joint>
    <right_joint>right_joint</right_joint>
    
    <!-- kinematics -->
    <wheel_separation>${wheel_separation}</wheel_separation>
    <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
    
    <!-- limits -->
    <max_wheel_torque>20</max_wheel_torque>
    <max_wheel_acceleration>5.0</max_wheel_acceleration>
    
    <!-- output -->
    <publish_odom>true</publish_odom>
    <publish_odom_tf>true</publish_odom_tf>
    <publish_wheel_tf>false</publish_wheel_tf>
    
    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_footprint</robot_base_frame>
    
    <!-- topics -->
    <command_topic>cmd_vel</command_topic>
    <odometry_topic>odom</odometry_topic>
  </plugin>
</gazebo>

<!-- Camera Plugin -->
<gazebo reference="camera_link">
  <sensor type="camera" name="camera1">
    <update_rate>30.0</update_rate>
    <camera name="head">
      <horizontal_fov>1.3962634</horizontal_fov>
      <image>
        <width>800</width>
        <height>600</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.02</near>
        <far>300</far>
      </clip>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.007</stddev>
      </noise>
    </camera>
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <ros>
        <namespace>/camera</namespace>
      </ros>
      <camera_name>camera1</camera_name>
      <frame_name>camera_link</frame_name>
      <hack_baseline>0.07</hack_baseline>
    </plugin>
  </sensor>
</gazebo>

<!-- 3D LiDAR Plugin (Velodyne VLP-16 simulation) -->
<gazebo reference="velodyne_base_link">
  <sensor type="ray" name="velodyne-VLP16">
    <pose>0 0 0 0 0 0</pose>
    <visualize>true</visualize>
    <update_rate>10</update_rate>
    <ray>
      <scan>
        <horizontal>
          <samples>440</samples>
          <resolution>1</resolution>
          <min_angle>-3.141592653589793</min_angle>
          <max_angle>3.141592653589793</max_angle>
        </horizontal>
        <vertical>
          <samples>16</samples>
          <resolution>1</resolution>
          <min_angle>-0.261799387799</min_angle>
          <max_angle>0.261799387799</max_angle>
        </vertical>
      </scan>
      <range>
        <min>0.3</min>
        <max>100.0</max>
        <resolution>0.001</resolution>
      </range>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.008</stddev>
      </noise>
    </ray>
    <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_velodyne_laser.so">
      <ros>
        <namespace>/velodyne</namespace>
      </ros>
      <topic_name>points</topic_name>
      <frame_name>velodyne_base_link</frame_name>
      <min_range>0.9</min_range>
      <max_range>130.0</max_range>
      <gaussian_noise>0.008</gaussian_noise>
    </plugin>
  </sensor>
</gazebo>

<!-- IMU Plugin -->
<gazebo reference="imu_link">
  <gravity>true</gravity>
  <sensor name="imu_sensor" type="imu">
    <always_on>true</always_on>
    <update_rate>100</update_rate>
    <visualize>true</visualize>
    <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
      <ros>
        <namespace>/imu</namespace>
      </ros>
      <topic_name>data</topic_name>
      <body_name>imu_link</body_name>
      <update_rate_hz>100.0</update_rate_hz>
      <gaussian_noise>0.01</gaussian_noise>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
      <frame_name>imu_link</frame_name>
      <initial_orientation_as_reference>false</initial_orientation_as_reference>
    </plugin>
    <pose>0 0 0 0 0 0</pose>
  </sensor>
</gazebo>

</robot>
